substitutions:
  _IMAGE_NAME: my-image # Configure this

steps:
- # Uses the Cloud Builders Gradle image.
  name: gcr.io/cloud-builders/gradle
  args:
  # Uncomment for projects that do not include Jib as a plugin.
  # - --init-script=auto-jib.gradle

  # Runs the Jib build.
  # For advanced customizations, configure the plugin in the build.gradle.
  - jib

  # This is necessary for Jib to find the credentials to use to push to your GCR repository.
  - -Duser.home=/builder/home

  # Sets the target image reference to push to.
  - --image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}
